apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: namespace-reader
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list"]
---



