apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  containers:
    - name: {{ .Values.appName }}
      image: docker.io/rkalluru/d79-{{ .Values.appName }}
